CREATE TABLE IF NOT EXISTS todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    name VARCHAR(100),
    phone VARCHAR(30),
    birthday DATE,
    order_history VARCHAR(100),
    monthly_visits VARCHAR(50),
    amount INTEGER,
    companion_count INTEGER,
    companion_memo VARCHAR(500),
    visit_date DATE,
    notes VARCHAR(1000),
    sales_trend_data CLOB,
    visit_count_trend_data CLOB,
    visit_date_trend_data CLOB,
    bottle_trend_data CLOB,
    completed BOOLEAN NOT NULL DEFAULT FALSE
);
