CREATE TABLE IF NOT EXISTS todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(30),
    birthday DATE,
    order_history VARCHAR(100),
    amount INTEGER,
    companion_count INTEGER,
    companion_memo VARCHAR(500),
    visit_date DATE,
    notes VARCHAR(1000),
    completed BOOLEAN NOT NULL DEFAULT FALSE
);
